### ISSUE TITLE
 RouteClassError is called when req.get_arg fails

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/bobtail#30]
If there are no arguments in the URI path & `req.get_arg` is called then `RouteClassError` is raised. 

Fix:
provide a new custom exception for this type of error.

**Comment by kousikmitra** [comment]
hey @joegasewicz,  can you provide a sample test case?

**Comment by joegasewicz** [comment]
> hey @joegasewicz, can you provide a sample test case?
> 
> I was trying with something like this but not getting RouteClassError
> 
> ```python
> def test_get_args_with_no_uri_path_args(self, bobtail_app, environ):
>         class Images:
> 
>             def get(self, req, res):
>                 pass
> 
>         routes = [
>             (Images(), "/images")
>         ]
> 
>         app = bobtail_app(routes=routes)
> 
>         env = environ(path="/images")
>         data = app(env, lambda s, r: None)
>         id = app.request.get_arg("id")
>         assert id == 1
> ```

If i have the following route:

```python
def get(self, req: Request, res: Response):
        req.get_arg("apples")
```

The registered route for this handler is `http://127.0.0.1:8000/images/{fruit:str}`  - obviously, for this handler to work i need to create a request like this -  `http://127.0.0.1:8000/images/apples`  

But if i just make a request using `http://127.0.0.1:8000/images` without the request arg then the `bobtail.exceptions.RouteClassError` is raised.

This is the stack trace:

```
[2022-12-03 11:32:53 +0000] [7307] [ERROR] Error handling request /images
Traceback (most recent call last):
  File "/home/joe/.local/share/virtualenvs/file_server-a96Bzucb/lib/python3.11/site-packages/bobtail/wsgi.py", line 63, in _call_handler
    self.middleware.call(self.request, self.response, handler)
  File "/home/joe/.local/share/virtualenvs/file_server-a96Bzucb/lib/python3.11/site-packages/bobtail/middleware.py", line 40, in call
    self.handler(self.request, self.response)
  File "/home/joe/GolandProjects/nottoboard/file_server/api/routes/images.py", line 8, in get
    req.get_arg("apples")
  File "/home/joe/.local/share/virtualenvs/file_server-a96Bzucb/lib/python3.11/site-packages/bobtail/request.py", line 40, in get_arg
    arg_value = self.args[name]["value"]
                ~~~~~~~~~^^^^^^
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joe/.local/share/virtualenvs/file_server-a96Bzucb/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/joe/.local/share/virtualenvs/file_server-a96Bzucb/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joe/.local/share/virtualenvs/file_server-a96Bzucb/lib/python3.11/site-packages/bobtail/wsgi.py", line 103, in __call__
    self._handle_route()
  File "/home/joe/.local/share/virtualenvs/file_server-a96Bzucb/lib/python3.11/site-packages/bobtail/wsgi.py", line 80, in _handle_route
    self._call_handler(route, "get")
  File "/home/joe/.local/share/virtualenvs/file_server-a96Bzucb/lib/python3.11/site-packages/bobtail/wsgi.py", line 65, in _call_handler
    raise RouteClassError("route class is not instantiated") from exc
bobtail.exceptions.RouteClassError: route class is not instantiated
```

**Comment by kousikmitra** [comment]
@joegasewicz got the issue. But wanted to understand something.
For a simple rest resource GET can work in two way where `GET /images` means get all resources(plural) and `GET /images/apple` for get single resource. Right now `bobtail` has only one `GET` method to implement. How do you intend implement both of them in one class?

**Comment by joegasewicz** [comment]
I think for this ticket we can create a custom error, then in the handler the caller can catch the exception if the handler expects to handle both `/apples` & `/apples/{fruit:str}` & the caller calls `req.get_arg("fruit")`. 

There is more work that will be added for the parser & the Bobtail class's route's kwargs but i want to push that back for now until we have a solid mvp. thank you

**Comment by kousikmitra** [comment]
In that case I think it would be better if `get_arg` returns a None value instead of throwing an exception?

**Comment by joegasewicz** [comment]
> In that case I think it would be better if `get_arg` returns a None value instead of throwing an exception?

Yea that would probably be a better solution

**Comment by joegasewicz** [comment]
This will work in conjunction with this https://github.com/joegasewicz/bobtail/issues/43

**Comment by kousikmitra** [comment]
raised a PR

Although the parser should be fixed cause something like below will fail
```
class Images:

            def get(self, req, res):
                pass

        routes = [
            (Images(), "/images/{id:int}/{name:str}")
        ]

        app = bobtail_app(routes=routes)

        env = environ(path="/images/1")
        data = app(env, lambda s, r: None)
        assert app.request.get_arg("id") == 1 #This is failing
        assert app.request.get_arg("name") == None
```

**Comment by joegasewicz** [comment]
> raised a PR
> 
> Although the parser should be fixed cause something like below will fail
> 
> ```
> class Images:
> 
>             def get(self, req, res):
>                 pass
> 
>         routes = [
>             (Images(), "/images/{id:int}/{name:str}")
>         ]
> 
>         app = bobtail_app(routes=routes)
> 
>         env = environ(path="/images/1")
>         data = app(env, lambda s, r: None)
>         assert app.request.get_arg("id") == 1 #This is failing
>         assert app.request.get_arg("name") == None
> ```

Yea the parser needs to recursively handle the multiple tokens in the URI... I promise to get that done by `0.1.0` - i'm just playing with some ideas / algorithms & also even to do this all in C with CPython... this will get done though in https://github.com/joegasewicz/bobtail/issues/22

**Comment by kousikmitra** [comment]
Great 🙌
